# Generated by Django 4.2.2 on 2023-06-11 17:46

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('logo', models.ImageField(default='', upload_to='api/restaurent/images/')),
                ('ratings', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('delivery_time', models.IntegerField()),
                ('live_discounts', models.CharField(max_length=150)),
                ('average_price', models.IntegerField()),
                ('cuisines', models.ManyToManyField(to='api.cuisine')),
            ],
        ),
    ]
