# Generated by Django 4.2.2 on 2023-06-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='image_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
