# Generated by Django 4.2.2 on 2023-07-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dish_menu_restaurent_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='cuisines',
            field=models.ManyToManyField(to='api.cuisine'),
        ),
    ]
