# Generated by Django 4.2.2 on 2023-07-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_home_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
