# Generated by Django 4.2.2 on 2023-07-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_menu_menu_home_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_home_image',
        ),
        migrations.AddField(
            model_name='restaurent',
            name='restaurent_page_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
