# Generated by Django 4.2.2 on 2023-07-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_menu_menu_home_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='is_displaying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='logo_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
